### ISSUE TITLE
[Question] Is everything local? Do you need something specific?

### ISSUE THREAD

**Issue by rjborba** [ParthSareen/obsidian-rag#1]
I've been working in a RAG project for a while.
I was thinking about build something like it to OBSIDIAN. I'm glade I found it. I would love to contribute with the project. Let me know how can I help you with that.

**Comment by ParthSareen** [comment]
Yup it's all local. I'm not actively maintaining this but happy to take PRs. If you're interested there are some things which I can leave open issues for!

**Comment by rjborba** [comment]
Please go for it. I'm in a time off between jobs and I have some time to spend.

**Comment by ParthSareen** [comment]
@rjborba here is a good place to start: https://github.com/ParthSareen/obsidian-rag/issues/2
