### ISSUE TITLE
Remove langchain, use ollama api

### ISSUE THREAD

**Issue by ParthSareen** [ParthSareen/obsidian-rag#2]
I had written this at a time where the Ollama api didn't exist.

There is a lot of bloat around langchain and I'd like to get to something a bit more performant, especially when indexing and piping the call to Ollama.

- [ ] Remove langchain dependancy 
- [ ] Implement the ollama api for calling the local models https://github.com/ollama/ollama-python 
- [ ] PR by showing a working interface

**Comment by AnkushMalaker** [comment]
I can take this up :)
Looks simple enough to do.

**Comment by ParthSareen** [comment]
Closing as new repo manages this https://github.com/ParthSareen/RAG-in-a-box
